apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatservice-mysql
spec:
  selector:
    matchLabels:
      app: chatservice-mysql
  template:
    metadata:
      labels:
        app: chatservice-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "chat_service"
---
apiVersion: v1
kind: Service
metadata:
  name: chatservice-mysql
spec:
  selector:
    app: chatservice-mysql
  ports:
    - port: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatservice
spec:
  selector:
    matchLabels:
      app: chatservice
  template:
    metadata:
      labels:
        app: chatservice
    spec:
      containers:
        - name: chatservice
          image: thiago1004/imersao-chatservice:v1
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 50051
              name: grpc
              protocol: TCP
          env:
            - name: DB_DRIVER
              value: mysql
            - name: DB_HOST
              value: chatservice-mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: root
            - name: DB_NAME
              value: chat_service
            - name: DB_PASSWORD
              value: root
            - name: WEB_SERVER_PORT
              value: "8080"
            - name: GRPC_SERVER_PORT
              value: "50051"          
---
apiVersion: v1
kind: Service
metadata:
  name: chatservice
spec:
  selector:
    app: chatservice
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http
    - port: 50051
      protocol: TCP
      name: grpc
