name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login  
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Docker build chatservice
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./chatservice
          file: ./chatservice/Dockerfile
          push: true
          tags: |
            thiago1004/imersao-chatservice:v${{ github.run_number }}
            thiago1004/imersao-chatservice:latest
      - name: Docker build webapp
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./webapp
          file: ./webapp/Dockerfile
          push: true
          tags: |
            thiago1004/imersao-gpt-webapp:v${{ github.run_number }}
            thiago1004/imersao-gpt-webapp:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
      - name: Autenticar o AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-session-token: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        run: echo "Configurar o aws configure"
      - name: Configurar o kubectl
        shell: bash
        run: |
          aws eks update-kubeconfig --name eks-imersao --region us-east-1
          
      - name: Deploy das aplicações
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            k8s/deploy-chatservice.yaml
          imagens: |
            thiago1004/imersao-chatservice:v${{ github.run_number }}
